// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv/kv.proto

package kms_kv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataNode struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataNode) Reset()         { *m = DataNode{} }
func (m *DataNode) String() string { return proto.CompactTextString(m) }
func (*DataNode) ProtoMessage()    {}
func (*DataNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{0}
}

func (m *DataNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNode.Unmarshal(m, b)
}
func (m *DataNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNode.Marshal(b, m, deterministic)
}
func (m *DataNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNode.Merge(m, src)
}
func (m *DataNode) XXX_Size() int {
	return xxx_messageInfo_DataNode.Size(m)
}
func (m *DataNode) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNode.DiscardUnknown(m)
}

var xxx_messageInfo_DataNode proto.InternalMessageInfo

func (m *DataNode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataNode) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type PutReq struct {
	Path                 string      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Dns                  []*DataNode `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PutReq) Reset()         { *m = PutReq{} }
func (m *PutReq) String() string { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()    {}
func (*PutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{1}
}

func (m *PutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReq.Unmarshal(m, b)
}
func (m *PutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReq.Marshal(b, m, deterministic)
}
func (m *PutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReq.Merge(m, src)
}
func (m *PutReq) XXX_Size() int {
	return xxx_messageInfo_PutReq.Size(m)
}
func (m *PutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReq.DiscardUnknown(m)
}

var xxx_messageInfo_PutReq proto.InternalMessageInfo

func (m *PutReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PutReq) GetDns() []*DataNode {
	if m != nil {
		return m.Dns
	}
	return nil
}

type PutRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRsp) Reset()         { *m = PutRsp{} }
func (m *PutRsp) String() string { return proto.CompactTextString(m) }
func (*PutRsp) ProtoMessage()    {}
func (*PutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{2}
}

func (m *PutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRsp.Unmarshal(m, b)
}
func (m *PutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRsp.Marshal(b, m, deterministic)
}
func (m *PutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRsp.Merge(m, src)
}
func (m *PutRsp) XXX_Size() int {
	return xxx_messageInfo_PutRsp.Size(m)
}
func (m *PutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PutRsp proto.InternalMessageInfo

func (m *PutRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PutRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type GetReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{3}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetRsp struct {
	Code                 string      `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string      `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Path                 string      `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Dns                  []*DataNode `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRsp) Reset()         { *m = GetRsp{} }
func (m *GetRsp) String() string { return proto.CompactTextString(m) }
func (*GetRsp) ProtoMessage()    {}
func (*GetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{4}
}

func (m *GetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRsp.Unmarshal(m, b)
}
func (m *GetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRsp.Marshal(b, m, deterministic)
}
func (m *GetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRsp.Merge(m, src)
}
func (m *GetRsp) XXX_Size() int {
	return xxx_messageInfo_GetRsp.Size(m)
}
func (m *GetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRsp proto.InternalMessageInfo

func (m *GetRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *GetRsp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetRsp) GetDns() []*DataNode {
	if m != nil {
		return m.Dns
	}
	return nil
}

type PatchReq struct {
	Path                 string      `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Dns                  []*DataNode `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PatchReq) Reset()         { *m = PatchReq{} }
func (m *PatchReq) String() string { return proto.CompactTextString(m) }
func (*PatchReq) ProtoMessage()    {}
func (*PatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{5}
}

func (m *PatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchReq.Unmarshal(m, b)
}
func (m *PatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchReq.Marshal(b, m, deterministic)
}
func (m *PatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchReq.Merge(m, src)
}
func (m *PatchReq) XXX_Size() int {
	return xxx_messageInfo_PatchReq.Size(m)
}
func (m *PatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_PatchReq proto.InternalMessageInfo

func (m *PatchReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PatchReq) GetDns() []*DataNode {
	if m != nil {
		return m.Dns
	}
	return nil
}

type PatchRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchRsp) Reset()         { *m = PatchRsp{} }
func (m *PatchRsp) String() string { return proto.CompactTextString(m) }
func (*PatchRsp) ProtoMessage()    {}
func (*PatchRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{6}
}

func (m *PatchRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchRsp.Unmarshal(m, b)
}
func (m *PatchRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchRsp.Marshal(b, m, deterministic)
}
func (m *PatchRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchRsp.Merge(m, src)
}
func (m *PatchRsp) XXX_Size() int {
	return xxx_messageInfo_PatchRsp.Size(m)
}
func (m *PatchRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PatchRsp proto.InternalMessageInfo

func (m *PatchRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PatchRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type ListReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{7}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Keys                 []string `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRsp) Reset()         { *m = ListRsp{} }
func (m *ListRsp) String() string { return proto.CompactTextString(m) }
func (*ListRsp) ProtoMessage()    {}
func (*ListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{8}
}

func (m *ListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRsp.Unmarshal(m, b)
}
func (m *ListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRsp.Marshal(b, m, deterministic)
}
func (m *ListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRsp.Merge(m, src)
}
func (m *ListRsp) XXX_Size() int {
	return xxx_messageInfo_ListRsp.Size(m)
}
func (m *ListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ListRsp proto.InternalMessageInfo

func (m *ListRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ListRsp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListRsp) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type DeleteReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{9}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRsp) Reset()         { *m = DeleteRsp{} }
func (m *DeleteRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteRsp) ProtoMessage()    {}
func (*DeleteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{10}
}

func (m *DeleteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRsp.Unmarshal(m, b)
}
func (m *DeleteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRsp.Marshal(b, m, deterministic)
}
func (m *DeleteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRsp.Merge(m, src)
}
func (m *DeleteRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteRsp.Size(m)
}
func (m *DeleteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRsp proto.InternalMessageInfo

func (m *DeleteRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeleteRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type RollbackReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackReq) Reset()         { *m = RollbackReq{} }
func (m *RollbackReq) String() string { return proto.CompactTextString(m) }
func (*RollbackReq) ProtoMessage()    {}
func (*RollbackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{11}
}

func (m *RollbackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackReq.Unmarshal(m, b)
}
func (m *RollbackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackReq.Marshal(b, m, deterministic)
}
func (m *RollbackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackReq.Merge(m, src)
}
func (m *RollbackReq) XXX_Size() int {
	return xxx_messageInfo_RollbackReq.Size(m)
}
func (m *RollbackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackReq.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackReq proto.InternalMessageInfo

func (m *RollbackReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RollbackRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRsp) Reset()         { *m = RollbackRsp{} }
func (m *RollbackRsp) String() string { return proto.CompactTextString(m) }
func (*RollbackRsp) ProtoMessage()    {}
func (*RollbackRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5993384bbd56d931, []int{12}
}

func (m *RollbackRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRsp.Unmarshal(m, b)
}
func (m *RollbackRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRsp.Marshal(b, m, deterministic)
}
func (m *RollbackRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRsp.Merge(m, src)
}
func (m *RollbackRsp) XXX_Size() int {
	return xxx_messageInfo_RollbackRsp.Size(m)
}
func (m *RollbackRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRsp proto.InternalMessageInfo

func (m *RollbackRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RollbackRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*DataNode)(nil), "kms.kv.DataNode")
	proto.RegisterType((*PutReq)(nil), "kms.kv.PutReq")
	proto.RegisterType((*PutRsp)(nil), "kms.kv.PutRsp")
	proto.RegisterType((*GetReq)(nil), "kms.kv.GetReq")
	proto.RegisterType((*GetRsp)(nil), "kms.kv.GetRsp")
	proto.RegisterType((*PatchReq)(nil), "kms.kv.PatchReq")
	proto.RegisterType((*PatchRsp)(nil), "kms.kv.PatchRsp")
	proto.RegisterType((*ListReq)(nil), "kms.kv.ListReq")
	proto.RegisterType((*ListRsp)(nil), "kms.kv.ListRsp")
	proto.RegisterType((*DeleteReq)(nil), "kms.kv.DeleteReq")
	proto.RegisterType((*DeleteRsp)(nil), "kms.kv.DeleteRsp")
	proto.RegisterType((*RollbackReq)(nil), "kms.kv.RollbackReq")
	proto.RegisterType((*RollbackRsp)(nil), "kms.kv.RollbackRsp")
}

func init() { proto.RegisterFile("kv/kv.proto", fileDescriptor_5993384bbd56d931) }

var fileDescriptor_5993384bbd56d931 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xb9, 0x4b, 0x1a, 0xef, 0xe6, 0xa0, 0x9e, 0x73, 0x28, 0x67, 0xac, 0x58, 0xf7, 0xa9,
	0xf4, 0x21, 0xd1, 0x14, 0x5f, 0x04, 0xa1, 0x48, 0xb5, 0x0f, 0x16, 0x39, 0x22, 0x08, 0x3e, 0x6e,
	0x93, 0xa5, 0x77, 0x6c, 0x9a, 0x8d, 0xdd, 0x6d, 0xa0, 0x88, 0x2f, 0x7e, 0x05, 0x3f, 0x87, 0x9f,
	0xc6, 0xaf, 0xe0, 0x07, 0x91, 0xcd, 0x66, 0x73, 0x77, 0xa9, 0x91, 0x1e, 0xf7, 0x36, 0xf9, 0xef,
	0xec, 0x6f, 0x66, 0xf6, 0x3f, 0x04, 0x46, 0xbc, 0x0c, 0x79, 0x19, 0x14, 0x57, 0x42, 0x09, 0xf4,
	0xf8, 0xa5, 0x0c, 0x78, 0xe9, 0xef, 0x5d, 0x08, 0x71, 0x91, 0xb1, 0x90, 0x16, 0x8b, 0x90, 0xe6,
	0xb9, 0x50, 0x54, 0x2d, 0x44, 0x2e, 0x4d, 0x16, 0x09, 0x60, 0x70, 0x42, 0x15, 0xfd, 0x28, 0x52,
	0x86, 0x63, 0x70, 0x38, 0xbb, 0x99, 0xf6, 0xf6, 0x7b, 0x07, 0xc3, 0x58, 0x87, 0x5a, 0x29, 0x69,
	0x36, 0xed, 0x1b, 0xa5, 0xa4, 0x19, 0x39, 0x06, 0x6f, 0x76, 0xad, 0x62, 0xf6, 0x15, 0x11, 0xdc,
	0x82, 0xaa, 0x79, 0x9d, 0x5e, 0xc5, 0x48, 0xc0, 0x49, 0x73, 0x39, 0xed, 0xef, 0x3b, 0x07, 0xa3,
	0x68, 0x1c, 0x98, 0x0e, 0x02, 0x5b, 0x20, 0xd6, 0x87, 0xe4, 0x85, 0x21, 0xc8, 0x42, 0x13, 0x12,
	0x91, 0x32, 0x4b, 0xd0, 0xb1, 0xd6, 0x52, 0x26, 0x93, 0xba, 0x64, 0x15, 0x93, 0x3d, 0xf0, 0x4e,
	0x59, 0x57, 0x4d, 0x32, 0x37, 0xa7, 0x77, 0xe7, 0x35, 0x14, 0xe7, 0x76, 0xe7, 0xee, 0xff, 0x3a,
	0x7f, 0x0b, 0x83, 0x19, 0x55, 0xc9, 0x7c, 0x9b, 0xe9, 0x23, 0xcb, 0xd8, 0x60, 0xfe, 0xa7, 0x70,
	0xef, 0x6c, 0x21, 0x3b, 0x1f, 0xe0, 0x4b, 0x7d, 0xbc, 0xe5, 0x0b, 0x20, 0xb8, 0x9c, 0xdd, 0x98,
	0x27, 0x18, 0xc6, 0x55, 0x4c, 0x9e, 0xc1, 0xf0, 0x84, 0x65, 0x4c, 0xb1, 0xae, 0xda, 0x47, 0x4d,
	0xc2, 0x06, 0xf3, 0x3c, 0x87, 0x51, 0x2c, 0xb2, 0xec, 0x9c, 0x26, 0xbc, 0x8b, 0xfb, 0x6a, 0x25,
	0xe5, 0xee, 0xe4, 0xe8, 0x97, 0x03, 0x3b, 0x1f, 0x3e, 0x7f, 0xba, 0x2a, 0xf1, 0x18, 0x9c, 0xd9,
	0xb5, 0xc2, 0x5d, 0xeb, 0x82, 0x59, 0x5a, 0x7f, 0xed, 0x5b, 0x16, 0xe4, 0xf1, 0x8f, 0xdf, 0x7f,
	0x7e, 0xf6, 0x27, 0x64, 0x37, 0xe4, 0x97, 0x32, 0x2c, 0x5f, 0x86, 0xdf, 0x74, 0xf9, 0xef, 0xaf,
	0x7b, 0x87, 0xf8, 0x06, 0x9c, 0x53, 0xb6, 0x42, 0x30, 0x2b, 0xe8, 0xaf, 0x7d, 0xcb, 0x82, 0x3c,
	0xaa, 0x08, 0x63, 0x6c, 0x11, 0xf0, 0x3d, 0xec, 0x54, 0x46, 0x63, 0xb3, 0x08, 0x76, 0x77, 0xfc,
	0x96, 0xb2, 0x6c, 0x23, 0xfa, 0x47, 0x1b, 0xef, 0xc0, 0xd5, 0xee, 0xe2, 0x7d, 0x7b, 0xa9, 0x5e,
	0x05, 0x7f, 0x5d, 0x90, 0x05, 0x79, 0x52, 0x41, 0x1e, 0xe2, 0xc4, 0x42, 0xb4, 0x85, 0xcb, 0x76,
	0x3c, 0x63, 0x14, 0x3e, 0x68, 0x16, 0xd3, 0x3a, 0xeb, 0xb7, 0xa5, 0xe5, 0x58, 0x87, 0xed, 0xb1,
	0xce, 0x60, 0x60, 0x8d, 0xc1, 0x89, 0xbd, 0xb6, 0xe2, 0xa6, 0x7f, 0x5b, 0xec, 0xa6, 0x9d, 0x7b,
	0xd5, 0x4f, 0xe8, 0xe8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xee, 0x81, 0x5b, 0xb9, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KVSrvClient is the client API for KVSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVSrvClient interface {
	Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutRsp, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error)
	Patch(ctx context.Context, in *PatchReq, opts ...grpc.CallOption) (*PatchRsp, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRsp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRsp, error)
	Rollback(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*RollbackRsp, error)
}

type kVSrvClient struct {
	cc *grpc.ClientConn
}

func NewKVSrvClient(cc *grpc.ClientConn) KVSrvClient {
	return &kVSrvClient{cc}
}

func (c *kVSrvClient) Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutRsp, error) {
	out := new(PutRsp)
	err := c.cc.Invoke(ctx, "/kms.kv.KVSrv/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSrvClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error) {
	out := new(GetRsp)
	err := c.cc.Invoke(ctx, "/kms.kv.KVSrv/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSrvClient) Patch(ctx context.Context, in *PatchReq, opts ...grpc.CallOption) (*PatchRsp, error) {
	out := new(PatchRsp)
	err := c.cc.Invoke(ctx, "/kms.kv.KVSrv/Patch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSrvClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRsp, error) {
	out := new(ListRsp)
	err := c.cc.Invoke(ctx, "/kms.kv.KVSrv/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSrvClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRsp, error) {
	out := new(DeleteRsp)
	err := c.cc.Invoke(ctx, "/kms.kv.KVSrv/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSrvClient) Rollback(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*RollbackRsp, error) {
	out := new(RollbackRsp)
	err := c.cc.Invoke(ctx, "/kms.kv.KVSrv/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVSrvServer is the server API for KVSrv service.
type KVSrvServer interface {
	Put(context.Context, *PutReq) (*PutRsp, error)
	Get(context.Context, *GetReq) (*GetRsp, error)
	Patch(context.Context, *PatchReq) (*PatchRsp, error)
	List(context.Context, *ListReq) (*ListRsp, error)
	Delete(context.Context, *DeleteReq) (*DeleteRsp, error)
	Rollback(context.Context, *RollbackReq) (*RollbackRsp, error)
}

// UnimplementedKVSrvServer can be embedded to have forward compatible implementations.
type UnimplementedKVSrvServer struct {
}

func (*UnimplementedKVSrvServer) Put(ctx context.Context, req *PutReq) (*PutRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedKVSrvServer) Get(ctx context.Context, req *GetReq) (*GetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedKVSrvServer) Patch(ctx context.Context, req *PatchReq) (*PatchRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (*UnimplementedKVSrvServer) List(ctx context.Context, req *ListReq) (*ListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedKVSrvServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedKVSrvServer) Rollback(ctx context.Context, req *RollbackReq) (*RollbackRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}

func RegisterKVSrvServer(s *grpc.Server, srv KVSrvServer) {
	s.RegisterService(&_KVSrv_serviceDesc, srv)
}

func _KVSrv_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSrvServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.kv.KVSrv/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSrvServer).Put(ctx, req.(*PutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVSrv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSrvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.kv.KVSrv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSrvServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVSrv_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSrvServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.kv.KVSrv/Patch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSrvServer).Patch(ctx, req.(*PatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVSrv_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSrvServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.kv.KVSrv/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSrvServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVSrv_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSrvServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.kv.KVSrv/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSrvServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVSrv_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSrvServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.kv.KVSrv/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSrvServer).Rollback(ctx, req.(*RollbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kms.kv.KVSrv",
	HandlerType: (*KVSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _KVSrv_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KVSrv_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _KVSrv_Patch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KVSrv_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KVSrv_Delete_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _KVSrv_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv/kv.proto",
}
