// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvhttp/kv_http.proto

package kvHttpPb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataNode struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataNode) Reset()         { *m = DataNode{} }
func (m *DataNode) String() string { return proto.CompactTextString(m) }
func (*DataNode) ProtoMessage()    {}
func (*DataNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{0}
}

func (m *DataNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNode.Unmarshal(m, b)
}
func (m *DataNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNode.Marshal(b, m, deterministic)
}
func (m *DataNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNode.Merge(m, src)
}
func (m *DataNode) XXX_Size() int {
	return xxx_messageInfo_DataNode.Size(m)
}
func (m *DataNode) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNode.DiscardUnknown(m)
}

var xxx_messageInfo_DataNode proto.InternalMessageInfo

func (m *DataNode) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataNode) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type PutReq struct {
	KeyPath              string      `protobuf:"bytes,1,opt,name=keyPath,proto3" json:"keyPath,omitempty"`
	Dns                  []*DataNode `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PutReq) Reset()         { *m = PutReq{} }
func (m *PutReq) String() string { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()    {}
func (*PutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{1}
}

func (m *PutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReq.Unmarshal(m, b)
}
func (m *PutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReq.Marshal(b, m, deterministic)
}
func (m *PutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReq.Merge(m, src)
}
func (m *PutReq) XXX_Size() int {
	return xxx_messageInfo_PutReq.Size(m)
}
func (m *PutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReq.DiscardUnknown(m)
}

var xxx_messageInfo_PutReq proto.InternalMessageInfo

func (m *PutReq) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

func (m *PutReq) GetDns() []*DataNode {
	if m != nil {
		return m.Dns
	}
	return nil
}

type PutRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRsp) Reset()         { *m = PutRsp{} }
func (m *PutRsp) String() string { return proto.CompactTextString(m) }
func (*PutRsp) ProtoMessage()    {}
func (*PutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{2}
}

func (m *PutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRsp.Unmarshal(m, b)
}
func (m *PutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRsp.Marshal(b, m, deterministic)
}
func (m *PutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRsp.Merge(m, src)
}
func (m *PutRsp) XXX_Size() int {
	return xxx_messageInfo_PutRsp.Size(m)
}
func (m *PutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PutRsp proto.InternalMessageInfo

func (m *PutRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PutRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type GetReq struct {
	KeyPath              string   `protobuf:"bytes,1,opt,name=keyPath,proto3" json:"keyPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{3}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

type GetRsp struct {
	Code                 string      `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string      `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Path                 string      `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Dns                  []*DataNode `protobuf:"bytes,4,rep,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRsp) Reset()         { *m = GetRsp{} }
func (m *GetRsp) String() string { return proto.CompactTextString(m) }
func (*GetRsp) ProtoMessage()    {}
func (*GetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{4}
}

func (m *GetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRsp.Unmarshal(m, b)
}
func (m *GetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRsp.Marshal(b, m, deterministic)
}
func (m *GetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRsp.Merge(m, src)
}
func (m *GetRsp) XXX_Size() int {
	return xxx_messageInfo_GetRsp.Size(m)
}
func (m *GetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRsp proto.InternalMessageInfo

func (m *GetRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *GetRsp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetRsp) GetDns() []*DataNode {
	if m != nil {
		return m.Dns
	}
	return nil
}

type PatchReq struct {
	KeyPath              string      `protobuf:"bytes,1,opt,name=keyPath,proto3" json:"keyPath,omitempty"`
	Dns                  []*DataNode `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PatchReq) Reset()         { *m = PatchReq{} }
func (m *PatchReq) String() string { return proto.CompactTextString(m) }
func (*PatchReq) ProtoMessage()    {}
func (*PatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{5}
}

func (m *PatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchReq.Unmarshal(m, b)
}
func (m *PatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchReq.Marshal(b, m, deterministic)
}
func (m *PatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchReq.Merge(m, src)
}
func (m *PatchReq) XXX_Size() int {
	return xxx_messageInfo_PatchReq.Size(m)
}
func (m *PatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_PatchReq proto.InternalMessageInfo

func (m *PatchReq) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

func (m *PatchReq) GetDns() []*DataNode {
	if m != nil {
		return m.Dns
	}
	return nil
}

type PatchRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchRsp) Reset()         { *m = PatchRsp{} }
func (m *PatchRsp) String() string { return proto.CompactTextString(m) }
func (*PatchRsp) ProtoMessage()    {}
func (*PatchRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{6}
}

func (m *PatchRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchRsp.Unmarshal(m, b)
}
func (m *PatchRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchRsp.Marshal(b, m, deterministic)
}
func (m *PatchRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchRsp.Merge(m, src)
}
func (m *PatchRsp) XXX_Size() int {
	return xxx_messageInfo_PatchRsp.Size(m)
}
func (m *PatchRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PatchRsp proto.InternalMessageInfo

func (m *PatchRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PatchRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type ListReq struct {
	KeyPath              string   `protobuf:"bytes,1,opt,name=keyPath,proto3" json:"keyPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{7}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

type ListRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Keys                 []string `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRsp) Reset()         { *m = ListRsp{} }
func (m *ListRsp) String() string { return proto.CompactTextString(m) }
func (*ListRsp) ProtoMessage()    {}
func (*ListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{8}
}

func (m *ListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRsp.Unmarshal(m, b)
}
func (m *ListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRsp.Marshal(b, m, deterministic)
}
func (m *ListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRsp.Merge(m, src)
}
func (m *ListRsp) XXX_Size() int {
	return xxx_messageInfo_ListRsp.Size(m)
}
func (m *ListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ListRsp proto.InternalMessageInfo

func (m *ListRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ListRsp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListRsp) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type DeleteReq struct {
	KeyPath              string   `protobuf:"bytes,1,opt,name=keyPath,proto3" json:"keyPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{9}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

type DeleteRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRsp) Reset()         { *m = DeleteRsp{} }
func (m *DeleteRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteRsp) ProtoMessage()    {}
func (*DeleteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{10}
}

func (m *DeleteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRsp.Unmarshal(m, b)
}
func (m *DeleteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRsp.Marshal(b, m, deterministic)
}
func (m *DeleteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRsp.Merge(m, src)
}
func (m *DeleteRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteRsp.Size(m)
}
func (m *DeleteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRsp proto.InternalMessageInfo

func (m *DeleteRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeleteRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type RollbackReq struct {
	KeyPath              string   `protobuf:"bytes,1,opt,name=keyPath,proto3" json:"keyPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackReq) Reset()         { *m = RollbackReq{} }
func (m *RollbackReq) String() string { return proto.CompactTextString(m) }
func (*RollbackReq) ProtoMessage()    {}
func (*RollbackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{11}
}

func (m *RollbackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackReq.Unmarshal(m, b)
}
func (m *RollbackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackReq.Marshal(b, m, deterministic)
}
func (m *RollbackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackReq.Merge(m, src)
}
func (m *RollbackReq) XXX_Size() int {
	return xxx_messageInfo_RollbackReq.Size(m)
}
func (m *RollbackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackReq.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackReq proto.InternalMessageInfo

func (m *RollbackReq) GetKeyPath() string {
	if m != nil {
		return m.KeyPath
	}
	return ""
}

type RollbackRsp struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRsp) Reset()         { *m = RollbackRsp{} }
func (m *RollbackRsp) String() string { return proto.CompactTextString(m) }
func (*RollbackRsp) ProtoMessage()    {}
func (*RollbackRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3430a6c17f1da92c, []int{12}
}

func (m *RollbackRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRsp.Unmarshal(m, b)
}
func (m *RollbackRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRsp.Marshal(b, m, deterministic)
}
func (m *RollbackRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRsp.Merge(m, src)
}
func (m *RollbackRsp) XXX_Size() int {
	return xxx_messageInfo_RollbackRsp.Size(m)
}
func (m *RollbackRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRsp proto.InternalMessageInfo

func (m *RollbackRsp) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RollbackRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*DataNode)(nil), "kms.http.kv.DataNode")
	proto.RegisterType((*PutReq)(nil), "kms.http.kv.PutReq")
	proto.RegisterType((*PutRsp)(nil), "kms.http.kv.PutRsp")
	proto.RegisterType((*GetReq)(nil), "kms.http.kv.GetReq")
	proto.RegisterType((*GetRsp)(nil), "kms.http.kv.GetRsp")
	proto.RegisterType((*PatchReq)(nil), "kms.http.kv.PatchReq")
	proto.RegisterType((*PatchRsp)(nil), "kms.http.kv.PatchRsp")
	proto.RegisterType((*ListReq)(nil), "kms.http.kv.ListReq")
	proto.RegisterType((*ListRsp)(nil), "kms.http.kv.ListRsp")
	proto.RegisterType((*DeleteReq)(nil), "kms.http.kv.DeleteReq")
	proto.RegisterType((*DeleteRsp)(nil), "kms.http.kv.DeleteRsp")
	proto.RegisterType((*RollbackReq)(nil), "kms.http.kv.RollbackReq")
	proto.RegisterType((*RollbackRsp)(nil), "kms.http.kv.RollbackRsp")
}

func init() { proto.RegisterFile("kvhttp/kv_http.proto", fileDescriptor_3430a6c17f1da92c) }

var fileDescriptor_3430a6c17f1da92c = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xd5, 0xa6, 0x74, 0xed, 0xe9, 0x0d, 0x9c, 0x8d, 0x2a, 0x44, 0x13, 0x9a, 0x8c, 0xd0,
	0xa6, 0x5d, 0x24, 0xd0, 0x89, 0x1b, 0x2e, 0xd1, 0xa4, 0x21, 0xc6, 0x50, 0x94, 0x5d, 0x8d, 0x1b,
	0xe4, 0xb6, 0xd6, 0x5a, 0x39, 0xad, 0xcd, 0xec, 0x59, 0xaa, 0x10, 0x37, 0xbc, 0x02, 0x8f, 0xc6,
	0x2b, 0xf0, 0x1e, 0x20, 0xdb, 0x09, 0x6b, 0x68, 0xe8, 0x56, 0xb1, 0xab, 0x1e, 0x7f, 0x3d, 0xfe,
	0xf9, 0xfc, 0xf9, 0x14, 0xd8, 0xe1, 0x66, 0xa2, 0xb5, 0x4c, 0xb8, 0xf9, 0x64, 0x7f, 0x63, 0x79,
	0x25, 0xb4, 0xc0, 0x1e, 0x9f, 0xa9, 0xd8, 0x9d, 0xb9, 0x89, 0x76, 0x2f, 0x85, 0xb8, 0xcc, 0x59,
	0x42, 0xe5, 0x34, 0xa1, 0xf3, 0xb9, 0xd0, 0x54, 0x4f, 0xc5, 0x5c, 0xf9, 0x54, 0x12, 0x43, 0xe7,
	0x98, 0x6a, 0xfa, 0x41, 0x8c, 0x19, 0x3e, 0x84, 0x80, 0xb3, 0x45, 0xd8, 0xd8, 0x6b, 0x1c, 0x74,
	0x33, 0x1b, 0x5a, 0xc5, 0xd0, 0x3c, 0x6c, 0x7a, 0xc5, 0xd0, 0x9c, 0x9c, 0x42, 0x3b, 0xbd, 0xd6,
	0x19, 0xfb, 0x8c, 0x21, 0x6c, 0x71, 0xb6, 0x48, 0xa9, 0x9e, 0x14, 0x37, 0xca, 0x23, 0xee, 0x43,
	0x30, 0x9e, 0xab, 0xb0, 0xb9, 0x17, 0x1c, 0xf4, 0x06, 0x8f, 0xe3, 0xa5, 0x62, 0xe2, 0xf2, 0xad,
	0xcc, 0x66, 0x90, 0x17, 0x1e, 0xa6, 0x24, 0x22, 0xb4, 0x46, 0x62, 0xcc, 0x0a, 0x92, 0x8b, 0xad,
	0x36, 0x66, 0x6a, 0x54, 0xbc, 0xee, 0x62, 0x42, 0xa0, 0x7d, 0xc2, 0xd6, 0x3f, 0x4f, 0x66, 0x3e,
	0xe7, 0xee, 0x54, 0xab, 0x49, 0x0b, 0x0a, 0xbc, 0x26, 0x97, 0x9a, 0x68, 0xdd, 0xda, 0xc4, 0x19,
	0x74, 0x52, 0xaa, 0x47, 0x93, 0x7b, 0x9a, 0xc9, 0xa0, 0xc4, 0x6d, 0x30, 0x95, 0x67, 0xb0, 0xf5,
	0x7e, 0xaa, 0x6e, 0x19, 0xcb, 0x45, 0x91, 0xf4, 0x9f, 0x73, 0x41, 0x68, 0x71, 0xb6, 0xf0, 0x83,
	0xe9, 0x66, 0x2e, 0x26, 0xcf, 0xa1, 0x7b, 0xcc, 0x72, 0xa6, 0xd9, 0xfa, 0x0a, 0x8e, 0xfe, 0xa4,
	0x6d, 0xd0, 0xdb, 0x3e, 0xf4, 0x32, 0x91, 0xe7, 0x43, 0x3a, 0xe2, 0xeb, 0xe9, 0xaf, 0x96, 0x12,
	0xef, 0xce, 0x1f, 0xfc, 0x0a, 0xa0, 0x7b, 0x6a, 0xde, 0x6a, 0x2d, 0xcf, 0xaf, 0x0c, 0x9e, 0x41,
	0x90, 0x5e, 0x6b, 0xdc, 0xae, 0x2c, 0xc8, 0x1b, 0x3e, 0x5a, 0x15, 0x95, 0x24, 0xbb, 0xdf, 0x7e,
	0xfc, 0xfc, 0xde, 0xec, 0x93, 0x47, 0x89, 0x79, 0x99, 0xf0, 0x99, 0x4a, 0xbe, 0x14, 0xf5, 0x7c,
	0x7d, 0xdd, 0x38, 0xc4, 0x77, 0x10, 0x9c, 0xb0, 0xbf, 0x71, 0xde, 0xc0, 0xd1, 0xaa, 0xa8, 0x24,
	0x79, 0xe2, 0x70, 0xdb, 0xb8, 0x8a, 0xc3, 0x73, 0x78, 0xe0, 0x8c, 0x81, 0x55, 0xf7, 0x94, 0xde,
	0x8b, 0xea, 0xe4, 0x9b, 0x02, 0x07, 0xf5, 0x05, 0x66, 0xd0, 0xb2, 0xa6, 0xc0, 0x9d, 0xca, 0xe5,
	0xc2, 0x4c, 0x51, 0x8d, 0xaa, 0x24, 0x79, 0xea, 0x88, 0x21, 0xf6, 0x4b, 0xa2, 0xf5, 0x40, 0xa5,
	0xd0, 0xb6, 0x5f, 0x33, 0xf6, 0xab, 0x3e, 0x2f, 0x2d, 0x12, 0xd5, 0xea, 0x37, 0xdd, 0x1f, 0xd6,
	0x74, 0x7f, 0x01, 0x9d, 0x72, 0xbb, 0x18, 0x56, 0xae, 0x2f, 0xb9, 0x23, 0xfa, 0xc7, 0x3f, 0x6b,
	0xd1, 0x6f, 0xe0, 0x63, 0x87, 0x3b, 0x03, 0xa4, 0xc3, 0x61, 0xdb, 0x7d, 0x15, 0x8f, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0x5e, 0xb5, 0x35, 0x58, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvHttpSrvClient is the client API for KvHttpSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvHttpSrvClient interface {
	Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutRsp, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error)
	// update: append data by key path
	Patch(ctx context.Context, in *PatchReq, opts ...grpc.CallOption) (*PatchRsp, error)
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRsp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRsp, error)
	Rollback(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*RollbackRsp, error)
}

type kvHttpSrvClient struct {
	cc *grpc.ClientConn
}

func NewKvHttpSrvClient(cc *grpc.ClientConn) KvHttpSrvClient {
	return &kvHttpSrvClient{cc}
}

func (c *kvHttpSrvClient) Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutRsp, error) {
	out := new(PutRsp)
	err := c.cc.Invoke(ctx, "/kms.http.kv.KvHttpSrv/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvHttpSrvClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error) {
	out := new(GetRsp)
	err := c.cc.Invoke(ctx, "/kms.http.kv.KvHttpSrv/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvHttpSrvClient) Patch(ctx context.Context, in *PatchReq, opts ...grpc.CallOption) (*PatchRsp, error) {
	out := new(PatchRsp)
	err := c.cc.Invoke(ctx, "/kms.http.kv.KvHttpSrv/Patch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvHttpSrvClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListRsp, error) {
	out := new(ListRsp)
	err := c.cc.Invoke(ctx, "/kms.http.kv.KvHttpSrv/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvHttpSrvClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRsp, error) {
	out := new(DeleteRsp)
	err := c.cc.Invoke(ctx, "/kms.http.kv.KvHttpSrv/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvHttpSrvClient) Rollback(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*RollbackRsp, error) {
	out := new(RollbackRsp)
	err := c.cc.Invoke(ctx, "/kms.http.kv.KvHttpSrv/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvHttpSrvServer is the server API for KvHttpSrv service.
type KvHttpSrvServer interface {
	Put(context.Context, *PutReq) (*PutRsp, error)
	Get(context.Context, *GetReq) (*GetRsp, error)
	// update: append data by key path
	Patch(context.Context, *PatchReq) (*PatchRsp, error)
	List(context.Context, *ListReq) (*ListRsp, error)
	Delete(context.Context, *DeleteReq) (*DeleteRsp, error)
	Rollback(context.Context, *RollbackReq) (*RollbackRsp, error)
}

// UnimplementedKvHttpSrvServer can be embedded to have forward compatible implementations.
type UnimplementedKvHttpSrvServer struct {
}

func (*UnimplementedKvHttpSrvServer) Put(ctx context.Context, req *PutReq) (*PutRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedKvHttpSrvServer) Get(ctx context.Context, req *GetReq) (*GetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedKvHttpSrvServer) Patch(ctx context.Context, req *PatchReq) (*PatchRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Patch not implemented")
}
func (*UnimplementedKvHttpSrvServer) List(ctx context.Context, req *ListReq) (*ListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedKvHttpSrvServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedKvHttpSrvServer) Rollback(ctx context.Context, req *RollbackReq) (*RollbackRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}

func RegisterKvHttpSrvServer(s *grpc.Server, srv KvHttpSrvServer) {
	s.RegisterService(&_KvHttpSrv_serviceDesc, srv)
}

func _KvHttpSrv_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvHttpSrvServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.http.kv.KvHttpSrv/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvHttpSrvServer).Put(ctx, req.(*PutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvHttpSrv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvHttpSrvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.http.kv.KvHttpSrv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvHttpSrvServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvHttpSrv_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvHttpSrvServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.http.kv.KvHttpSrv/Patch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvHttpSrvServer).Patch(ctx, req.(*PatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvHttpSrv_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvHttpSrvServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.http.kv.KvHttpSrv/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvHttpSrvServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvHttpSrv_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvHttpSrvServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.http.kv.KvHttpSrv/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvHttpSrvServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvHttpSrv_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvHttpSrvServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.http.kv.KvHttpSrv/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvHttpSrvServer).Rollback(ctx, req.(*RollbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KvHttpSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kms.http.kv.KvHttpSrv",
	HandlerType: (*KvHttpSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _KvHttpSrv_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KvHttpSrv_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _KvHttpSrv_Patch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KvHttpSrv_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KvHttpSrv_Delete_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _KvHttpSrv_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvhttp/kv_http.proto",
}
